[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#020617"
secondaryBackgroundColor = "#111827"
textColor = "#E5E7EB"
font = "sans serif"

[server]
headless = true
maxUploadSize = 200
runOnSave = true

[browser]
gatherUsageStats = false
